### ISSUE TITLE
Why is python file called by ProcessBuilder in your DRLDatacenter file, and python3 DeepRL.py operation is required in your README.md?

### ISSUE THREAD

**Issue by daviddavid888** [Cloudslab/DLSF#5]

**Comment by shreshthtuli** [comment]
In some systems there are permission conflicts. To avoid problems you may run python file in separate terminal.

**Comment by daviddavid888** [comment]
> 在某些系统中，存在权限冲突。为了避免出现问题，您可以在单独的终端中运行python文件。



> 在某些系统中，存在权限冲突。为了避免出现问题，您可以在单独的终端中运行python文件。



> In some systems there are permission conflicts. To avoid problems you may run python file in separate terminal.

Need a separate terminal to run the DeepRL.py file and then run the DeepRLRunner.java file? But this is two programs that cannot pass parameters to each other.

**Comment by daviddavid888** [comment]
> In some systems there are permission conflicts. To avoid problems you may run python file in separate terminal.

Need a separate terminal to run the DeepRL.py file and then run the DeepRLRunner.java file? But this is two programs that cannot pass parameters to each other.
